"""Initial

Revision ID: 2394c4a91f13
Revises: 
Create Date: 2021-04-27 03:24:59.772271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2394c4a91f13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
                    sa.Column('student_id', sa.INTEGER(), nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), nullable=True),
                    sa.Column('last_name', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('student_id')
                    )
    op.create_table('homework',
                    sa.Column('homework_id', sa.INTEGER(), nullable=False),
                    sa.Column('task_text', sa.VARCHAR(), nullable=True),
                    sa.Column('deadline', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('homework_id')
                    )
    op.create_table('homework_result',
                    sa.Column('homework_id', sa.INTEGER(), nullable=False),
                    sa.Column('solution', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('homework_id')
                    )
    op.create_table('teacher',
                    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), nullable=True),
                    sa.Column('last_name', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('teacher_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('homework_result')
    op.drop_table('homework')
    op.drop_table('student')
    # ### end Alembic commands ###
